import { contextBridge, ipcRenderer } from 'electron'

console.log('[AaronClaw] Build v3.0.0-hotfix-' + Date.now())

contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveConfig: (c: any) => ipcRenderer.invoke('config:save', c),
  convList: () => ipcRenderer.invoke('conv:list'),
  convCreate: (t: string, m?: string, agentId?: string) => ipcRenderer.invoke('conv:create', t, m, agentId),
  convDelete: (id: string) => ipcRenderer.invoke('conv:delete', id),
  convMessages: (cid: string) => ipcRenderer.invoke('conv:messages', cid),
  convSave: (cid: string, role: string, content: string) => ipcRenderer.invoke('conv:saveMessage', cid, role, content),
  convFork: (cid: string, idx: number) => ipcRenderer.invoke('conv:fork', cid, idx),
  agentsList: () => ipcRenderer.invoke('agents:list'),
  agentsSave: (a: any) => ipcRenderer.invoke('agents:save', a),
  agentsDelete: (id: string) => ipcRenderer.invoke('agents:delete', id),
  agentsToggle: (id: string, en: boolean) => ipcRenderer.invoke('agents:toggle', id, en),
  providersList: () => ipcRenderer.invoke('providers:list'),
  providersSave: (p: any) => ipcRenderer.invoke('providers:save', p),
  providersDelete: (id: string) => ipcRenderer.invoke('providers:delete', id),
  providersToggle: (id: string, en: boolean) => ipcRenderer.invoke('providers:toggle', id, en),
  modelsList: () => ipcRenderer.invoke('models:list'),
  modelsSave: (m: any) => ipcRenderer.invoke('models:save', m),
  modelsDelete: (id: string) => ipcRenderer.invoke('models:delete', id),
  modelsToggle: (id: string, en: boolean) => ipcRenderer.invoke('models:toggle', id, en),
  skillsList: () => ipcRenderer.invoke('skills:list'),
  skillsSave: (item: any) => ipcRenderer.invoke('skills:save', item),
  skillsDelete: (id: string) => ipcRenderer.invoke('skills:delete', id),
  skillsToggle: (id: string, en: boolean) => ipcRenderer.invoke('skills:toggle', id, en),
  memoryList: () => ipcRenderer.invoke('memory:list'),
  memorySearch: (q: string) => ipcRenderer.invoke('memory:search', q),
  memoryAdd: (c: string, cat: string) => ipcRenderer.invoke('memory:add', c, cat),
  memoryDelete: (id: string) => ipcRenderer.invoke('memory:delete', id),
  cronList: () => ipcRenderer.invoke('cron:list'),
  cronSave: (j: any) => ipcRenderer.invoke('cron:save', j),
  cronDelete: (id: string) => ipcRenderer.invoke('cron:delete', id),
  cronHistory: (jobId?: string) => ipcRenderer.invoke('cron:history', jobId),
  mcpList: () => ipcRenderer.invoke('mcp:list'),
  mcpSave: (s: any) => ipcRenderer.invoke('mcp:save', s),
  mcpConnect: (id: string) => ipcRenderer.invoke('mcp:connect', id),
  mcpDisconnect: (id: string) => ipcRenderer.invoke('mcp:disconnect', id),
  mcpCallTool: (serverId: string, toolName: string, args: any) => ipcRenderer.invoke('mcp:callTool', serverId, toolName, args),
  mcpTools: () => ipcRenderer.invoke('mcp:tools'),
  mcpStatus: (id: string) => ipcRenderer.invoke('mcp:status', id),
  toolsHealth: () => ipcRenderer.invoke('tools:health'),
  toolsStats: () => ipcRenderer.invoke('tools:stats'),
  toolsReliable: () => ipcRenderer.invoke('tools:reliable'),
  toolsUnreliable: () => ipcRenderer.invoke('tools:unreliable'),
  patternsTop: (limit?: number) => ipcRenderer.invoke('patterns:top', limit),
  skillsValidate: (execute: string) => ipcRenderer.invoke('skills:validate', execute),
  generatedFilesList: () => ipcRenderer.invoke('generatedFiles:list'),
  generatedFilesDelete: (id: string) => ipcRenderer.invoke('generatedFiles:delete', id),
  generatedFilesClear: () => ipcRenderer.invoke('generatedFiles:clear'),
  gcGroups: () => ipcRenderer.invoke('gc:groups'),
  gcMessages: (gid: string) => ipcRenderer.invoke('gc:messages', gid),
  gcSend: (gid: string, msg: string) => ipcRenderer.invoke('gc:sendMessage', gid, msg),
  gcMembers: (gid: string) => ipcRenderer.invoke('gc:members', gid),
  gcAddMember: (gid: string, aid: string) => ipcRenderer.invoke('gc:addMember', gid, aid),
  gcSave: (group: any) => ipcRenderer.invoke('gc:save', group),
  gcBookmark: (id: string) => ipcRenderer.invoke('gc:bookmark', id),
  gcUnbookmark: (id: string) => ipcRenderer.invoke('gc:unbookmark', id),
  gcBookmarks: (gid: string) => ipcRenderer.invoke('gc:bookmarks', gid),
  gcDelete: (id: string) => ipcRenderer.invoke('gc:delete', id),
  gcPin: (id: string) => ipcRenderer.invoke('gc:pin', id),
  gcPinned: (gid: string) => ipcRenderer.invoke('gc:pinned', gid),
  gatewayStatus: () => ipcRenderer.invoke('gateway:status'),
  gatewayStart: () => ipcRenderer.invoke('gateway:start'),
  gatewayCircuit: () => ipcRenderer.invoke('gateway:circuit'),
  chatSend: (opts: any) => ipcRenderer.invoke('chat:send', opts),
  chatCancel: () => ipcRenderer.invoke('chat:cancel'),
  chatFeedback: (opts: any) => ipcRenderer.invoke('chat:feedback', opts),
  chatDispatch: (opts: any) => ipcRenderer.invoke('chat:dispatch', opts),
  onDispatchStart: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:dispatch:start'); ipcRenderer.on('chat:dispatch:start', (_, d) => cb(d)) },
  onDispatchProgress: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:dispatch:progress'); ipcRenderer.on('chat:dispatch:progress', (_, d) => cb(d)) },
  onDispatchDone: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:dispatch:done'); ipcRenderer.on('chat:dispatch:done', (_, d) => cb(d)) },
  onChatToken: (cb: (t: string) => void) => { ipcRenderer.removeAllListeners('chat:token'); ipcRenderer.on('chat:token', (_, t) => cb(t)) },
  onChatThinking: (cb: (t: string) => void) => { ipcRenderer.removeAllListeners('chat:thinking'); ipcRenderer.on('chat:thinking', (_, t) => cb(t)) },
  onChatToolCall: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:toolCall'); ipcRenderer.on('chat:toolCall', (_, d) => cb(d)) },
  onChatStage: (cb: (stage: string) => void) => { ipcRenderer.removeAllListeners('chat:stage'); ipcRenderer.on('chat:stage', (_, s) => cb(s)) },
  onChatDone: (cb: (t: string, thinking?: string, toolCalls?: any[]) => void) => { ipcRenderer.removeAllListeners('chat:done'); ipcRenderer.on('chat:done', (_, t, thinking, toolCalls) => cb(t, thinking, toolCalls)) },
  onChatError: (cb: (e: string) => void) => { ipcRenderer.removeAllListeners('chat:error'); ipcRenderer.on('chat:error', (_, e) => cb(e)) },
  onGcToken: (cb: (t: string) => void) => { ipcRenderer.removeAllListeners('gc:token'); ipcRenderer.on('gc:token', (_, t) => cb(t)) },
  onGcDone: (cb: (t: string) => void) => { ipcRenderer.removeAllListeners('gc:done'); ipcRenderer.on('gc:done', (_, t) => cb(t)) },
  filesList: (dir?: string) => ipcRenderer.invoke('files:list', dir),
  filesOpen: (fp: string) => ipcRenderer.invoke('files:openExternal', fp),
  systemInfo: () => ipcRenderer.invoke('system:info'),
  settingsGet: (key: string) => ipcRenderer.invoke('settings:get', key),
  settingsSet: (key: string, val: any) => ipcRenderer.invoke('settings:set', key, val),
  draftSave: (convId: string, text: string) => ipcRenderer.invoke('draft:save', convId, text),
  draftGet: (convId: string) => ipcRenderer.invoke('draft:get', convId),
  dataExport: () => ipcRenderer.invoke('data:export'),
  dataImport: (path: string) => ipcRenderer.invoke('data:import', path),
  healthCheck: () => ipcRenderer.invoke('health:check'),
  cryptoEncrypt: (text: string) => ipcRenderer.invoke('crypto:encrypt', text),
  cryptoDecrypt: (encoded: string) => ipcRenderer.invoke('crypto:decrypt', encoded),
  notify: (title: string, body: string) => ipcRenderer.invoke('notify', title, body),
  capTts: (text: string, voice?: string) => ipcRenderer.invoke('cap:tts', text, voice),
  capImageGen: (prompt: string, size?: string) => ipcRenderer.invoke('cap:imageGen', prompt, size),
  capTranscribe: (audioPath: string) => ipcRenderer.invoke('cap:transcribe', audioPath),
  capDocExtract: (filePath: string) => ipcRenderer.invoke('cap:docExtract', filePath),
  capWebSearch: (query: string) => ipcRenderer.invoke('cap:webSearch', query),
  capEmbed: (text: string) => ipcRenderer.invoke('cap:embed', text),
  capPlayAudio: (path: string) => ipcRenderer.invoke('cap:playAudio', path),
  onAudioReady: (cb: (path: string) => void) => { ipcRenderer.removeAllListeners('cap:audioReady'); ipcRenderer.on('cap:audioReady', (_, p) => cb(p)) },
  // Voice
  voiceStart: () => ipcRenderer.invoke('voice:start'),
  voiceChunk: (chunk: string) => ipcRenderer.invoke('voice:chunk', chunk),
  voiceStop: () => ipcRenderer.invoke('voice:stop'),
  // RAG
  ragImport: (path: string) => ipcRenderer.invoke('rag:import', path),
  ragList: () => ipcRenderer.invoke('rag:list'),
  ragDelete: (id: string) => ipcRenderer.invoke('rag:delete', id),
  ragSearch: (q: string, topK?: number) => ipcRenderer.invoke('rag:search', q, topK),
  // Workflows
  wfList: () => ipcRenderer.invoke('wf:list'),
  wfSave: (wf: any) => ipcRenderer.invoke('wf:save', wf),
  wfDelete: (id: string) => ipcRenderer.invoke('wf:delete', id),
  wfExecute: (id: string, input: string) => ipcRenderer.invoke('wf:execute', id, input),
  wfPresets: () => ipcRenderer.invoke('wf:presets'),
  // Backup
  backupCreate: () => ipcRenderer.invoke('backup:create'),
  backupList: () => ipcRenderer.invoke('backup:list'),
  backupRestore: (path: string) => ipcRenderer.invoke('backup:restore', path),
  // Prompts
  promptsList: () => ipcRenderer.invoke('prompts:list'),
  promptsSave: (p: any) => ipcRenderer.invoke('prompts:save', p),
  promptsDelete: (id: string) => ipcRenderer.invoke('prompts:delete', id),
  // Search
  searchMessages: (q: string, limit?: number) => ipcRenderer.invoke('search:messages', q, limit),
  // Logs
  logsList: () => ipcRenderer.invoke('logs:list'),
  logsRead: (f: string) => ipcRenderer.invoke('logs:read', f),
  logsDir: () => ipcRenderer.invoke('logs:dir'),
})