import { contextBridge, ipcRenderer } from 'electron'

console.log('[MiClaw] Build v3.0.0-hotfix-' + Date.now())

contextBridge.exposeInMainWorld('api', {
  minimize: () => ipcRenderer.invoke('window:minimize'),
  maximize: () => ipcRenderer.invoke('window:maximize'),
  close: () => ipcRenderer.invoke('window:close'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  saveConfig: (c: any) => ipcRenderer.invoke('config:save', c),
  convList: () => ipcRenderer.invoke('conv:list'),
  convCreate: (t: string, m?: string, agentId?: string) => ipcRenderer.invoke('conv:create', t, m, agentId),
  convDelete: (id: string) => ipcRenderer.invoke('conv:delete', id),
  convMessages: (cid: string) => ipcRenderer.invoke('conv:messages', cid),
  convSave: (cid: string, role: string, content: string, toolCalls?: string, thinking?: string) => ipcRenderer.invoke('conv:saveMessage', cid, role, content, toolCalls, thinking),
  convUpdateTitle: (cid: string, title: string) => ipcRenderer.invoke('conv:updateTitle', cid, title),
  convFork: (cid: string, idx: number) => ipcRenderer.invoke('conv:fork', cid, idx),
  agentsList: () => ipcRenderer.invoke('agents:list'),
  agentsSave: (a: any) => ipcRenderer.invoke('agents:save', a),
  agentsDelete: (id: string) => ipcRenderer.invoke('agents:delete', id),
  agentsToggle: (id: string, en: boolean) => ipcRenderer.invoke('agents:toggle', id, en),
  providersList: () => ipcRenderer.invoke('providers:list'),
  providersSave: (p: any) => ipcRenderer.invoke('providers:save', p),
  providersDelete: (id: string) => ipcRenderer.invoke('providers:delete', id),
  providersToggle: (id: string, en: boolean) => ipcRenderer.invoke('providers:toggle', id, en),
  modelsList: () => ipcRenderer.invoke('models:list'),
  modelsSave: (m: any) => ipcRenderer.invoke('models:save', m),
  modelsDelete: (id: string) => ipcRenderer.invoke('models:delete', id),
  modelsToggle: (id: string, en: boolean) => ipcRenderer.invoke('models:toggle', id, en),
  // Calendar
  calendarCreate: (event: any) => ipcRenderer.invoke('calendar:create', event),
  calendarList: (startDate?: string, endDate?: string) => ipcRenderer.invoke('calendar:list', startDate, endDate),
  calendarUpcoming: () => ipcRenderer.invoke('calendar:upcoming'),
  calendarToday: () => ipcRenderer.invoke('calendar:today'),
  calendarUpdate: (id: string, updates: any) => ipcRenderer.invoke('calendar:update', id, updates),
  calendarDelete: (id: string) => ipcRenderer.invoke('calendar:delete', id),
  calendarReminders: (minutes?: number) => ipcRenderer.invoke('calendar:reminders', minutes),

  generatedFilesList: () => ipcRenderer.invoke('generatedFiles:list'),
  generatedFilesDelete: (id: string) => ipcRenderer.invoke('generatedFiles:delete', id),
  generatedFilesClear: () => ipcRenderer.invoke('generatedFiles:clear'),
  gcGroups: () => ipcRenderer.invoke('gc:groups'),
  gcMessages: (gid: string) => ipcRenderer.invoke('gc:messages', gid),
  gcSend: (gid: string, msg: string) => ipcRenderer.invoke('gc:sendMessage', gid, msg),
  gcMembers: (gid: string) => ipcRenderer.invoke('gc:members', gid),
  gcAddMember: (gid: string, aid: string) => ipcRenderer.invoke('gc:addMember', gid, aid),
  gcSave: (group: any) => ipcRenderer.invoke('gc:save', group),
  gcBookmark: (id: string) => ipcRenderer.invoke('gc:bookmark', id),
  gcUnbookmark: (id: string) => ipcRenderer.invoke('gc:unbookmark', id),
  gcBookmarks: (gid: string) => ipcRenderer.invoke('gc:bookmarks', gid),
  gcDelete: (id: string) => ipcRenderer.invoke('gc:delete', id),
  gcClearMessages: (gid: string) => ipcRenderer.invoke('gc:clearMessages', gid),
  gcPin: (id: string) => ipcRenderer.invoke('gc:pin', id),
  gcPinned: (gid: string) => ipcRenderer.invoke('gc:pinned', gid),
  // GC Streaming
  gcStreamSend: (gid: string, msg: string) => ipcRenderer.invoke('gc:stream:send', gid, msg),
  onGcStreamToken: (cb: (d: { groupId: string; token: string }) => void) => { ipcRenderer.removeAllListeners('gc:stream:token'); ipcRenderer.on('gc:stream:token', (_, d) => cb(d)) },
  onGcStreamThinking: (cb: (d: { groupId: string; text: string }) => void) => { ipcRenderer.removeAllListeners('gc:stream:thinking'); ipcRenderer.on('gc:stream:thinking', (_, d) => cb(d)) },
  onGcStreamTool: (cb: (d: { groupId: string; id: string; name: string; status: string; args?: string; error?: string }) => void) => { ipcRenderer.removeAllListeners('gc:stream:tool'); ipcRenderer.on('gc:stream:tool', (_, d) => cb(d)) },
  onGcStreamDone: (cb: (d: { groupId: string; text: string; thinking?: string; toolCalls?: any[] }) => void) => { ipcRenderer.removeAllListeners('gc:stream:done'); ipcRenderer.on('gc:stream:done', (_, d) => cb(d)) },
  onGcStreamError: (cb: (d: { groupId: string; error: string }) => void) => { ipcRenderer.removeAllListeners('gc:stream:error'); ipcRenderer.on('gc:stream:error', (_, d) => cb(d)) },
  onGcStreamDecomposition: (cb: (d: { groupId: string; steps: Array<{ id: string; agentId: string; agentName: string; task: string }> }) => void) => { ipcRenderer.removeAllListeners('gc:stream:decomposition'); ipcRenderer.on('gc:stream:decomposition', (_, d) => cb(d)) },
  onGcStreamSpeaker: (cb: (d: { groupId: string; agentId: string; agentName: string }) => void) => { ipcRenderer.removeAllListeners('gc:stream:speaker'); ipcRenderer.on('gc:stream:speaker', (_, d) => cb(d)) },
  gatewayStatus: () => ipcRenderer.invoke('gateway:status'),
  gatewayStart: () => ipcRenderer.invoke('gateway:start'),
  gatewayInfo: () => ipcRenderer.invoke('gateway:info'),
  // Templates
  templatesList: () => ipcRenderer.invoke('templates:list'),
  templatesSave: (t: any) => ipcRenderer.invoke('templates:save', t),
  templatesDelete: (id: string) => ipcRenderer.invoke('templates:delete', id),
  templatesForAgent: (agentId: string) => ipcRenderer.invoke('templates:forAgent', agentId),
  // TTS
  ttsSpeak: (text: string, lang?: string) => ipcRenderer.invoke('tts:speak', text, lang),
  ttsStop: () => ipcRenderer.invoke('tts:stop'),
  ttsVoices: () => ipcRenderer.invoke('tts:voices'),
  // Clipboard
  clipboardHistory: () => ipcRenderer.invoke('clipboard:history'),
  clipboardPick: (text: string) => ipcRenderer.invoke('clipboard:pick', text),
  clipboardClear: () => ipcRenderer.invoke('clipboard:clear'),

  chatSend: (opts: any) => ipcRenderer.invoke('chat:send', opts),
  chatCancel: () => ipcRenderer.invoke('chat:cancel'),
  chatCompare: (opts: any) => ipcRenderer.invoke('chat:compare', opts),
  ollamaStatus: () => ipcRenderer.invoke('ollama:status'),
  onChatToken: (cb: (t: string) => void) => { ipcRenderer.removeAllListeners('chat:token'); ipcRenderer.on('chat:token', (_, t) => cb(t)) },
  onChatThinking: (cb: (t: string) => void) => { ipcRenderer.removeAllListeners('chat:thinking'); ipcRenderer.on('chat:thinking', (_, t) => cb(t)) },
  onToolStatus: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:tool-status'); ipcRenderer.on('chat:tool-status', (_, d) => cb(d)) },
  onChatDone: (cb: (t: string, thinking?: string, toolCalls?: any[]) => void) => { ipcRenderer.removeAllListeners('chat:done'); ipcRenderer.on('chat:done', (_, t, thinking, toolCalls) => cb(t, thinking, toolCalls)) },
  onChatUsage: (cb: (u: any) => void) => { ipcRenderer.removeAllListeners('chat:usage'); ipcRenderer.on('chat:usage', (_, u) => cb(u)) },
  onChatModel: (cb: (m: string) => void) => { ipcRenderer.removeAllListeners('chat:model'); ipcRenderer.on('chat:model', (_, m) => cb(m)) },
  onChatError: (cb: (e: string) => void) => { ipcRenderer.removeAllListeners('chat:error'); ipcRenderer.on('chat:error', (_, e) => cb(e)) },
  onCompareResult: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:compare:result'); ipcRenderer.on('chat:compare:result', (_, d) => cb(d)) },
  onCompareToken: (cb: (d: { modelId: string; token: string }) => void) => { ipcRenderer.removeAllListeners('chat:compare:token'); ipcRenderer.on('chat:compare:token', (_, d) => cb(d)) },
  onCompareThinking: (cb: (d: { modelId: string; token: string }) => void) => { ipcRenderer.removeAllListeners('chat:compare:thinking'); ipcRenderer.on('chat:compare:thinking', (_, d) => cb(d)) },
  onCompareToolStatus: (cb: (d: any) => void) => { ipcRenderer.removeAllListeners('chat:compare:tool-status'); ipcRenderer.on('chat:compare:tool-status', (_, d) => cb(d)) },
  filesList: (dir?: string) => ipcRenderer.invoke('files:list', dir),
  filesRead: (fp: string) => ipcRenderer.invoke('files:read', fp),
  filesOpen: (fp: string) => ipcRenderer.invoke('files:openExternal', fp),
  systemInfo: () => ipcRenderer.invoke('system:info'),
  settingsGet: (key: string) => ipcRenderer.invoke('settings:get', key),
  settingsSet: (key: string, val: any) => ipcRenderer.invoke('settings:set', key, val),
  draftSave: (convId: string, text: string) => ipcRenderer.invoke('draft:save', convId, text),
  draftGet: (convId: string) => ipcRenderer.invoke('draft:get', convId),
  dataExport: () => ipcRenderer.invoke('data:export'),
  dataImport: (path: string) => ipcRenderer.invoke('data:import', path),
  healthCheck: () => ipcRenderer.invoke('health:check'),
  cryptoEncrypt: (text: string) => ipcRenderer.invoke('crypto:encrypt', text),
  cryptoDecrypt: (encoded: string) => ipcRenderer.invoke('crypto:decrypt', encoded),
  notify: (title: string, body: string) => ipcRenderer.invoke('notify', title, body),
  // Backup
  backupCreate: () => ipcRenderer.invoke('backup:create'),
  backupList: () => ipcRenderer.invoke('backup:list'),
  backupRestore: (path: string) => ipcRenderer.invoke('backup:restore', path),

  // Search
  searchMessages: (q: string, limit?: number) => ipcRenderer.invoke('search:messages', q, limit),
  // Logs
  logsList: () => ipcRenderer.invoke('logs:list'),
  logsRead: (f: string) => ipcRenderer.invoke('logs:read', f),
  logsDir: () => ipcRenderer.invoke('logs:dir'),
  // Channel management
  channelStatus: () => ipcRenderer.invoke('channel:status'),
  channelSetup: (channelId: string, credentials?: Record<string, string>) => ipcRenderer.invoke('channel:setup', channelId, credentials),
  channelDisconnect: (channelId: string) => ipcRenderer.invoke('channel:disconnect', channelId),
  channelWeixinQr: () => ipcRenderer.invoke('channel:weixin-qr'),
  channelWeixinPoll: (uuid: string) => ipcRenderer.invoke('channel:weixin-poll', uuid),
  // Plugins
  pluginsList: () => ipcRenderer.invoke('plugins:list'),
  pluginsDetails: (id: string) => ipcRenderer.invoke('plugins:details', id),
  pluginsOpenDir: () => ipcRenderer.invoke('plugins:openDir'),
  pluginsInstall: (id: string, source?: string) => ipcRenderer.invoke('plugins:install', id, source),
  pluginsUninstall: (id: string) => ipcRenderer.invoke('plugins:uninstall', id),
  pluginsSearch: (q: string) => ipcRenderer.invoke('plugins:search', q),
  pluginsCheckUpdates: () => ipcRenderer.invoke('plugins:checkUpdates'),
  // MCP Servers
  mcpList: () => ipcRenderer.invoke('mcp:list'),
  mcpSave: (s: any) => ipcRenderer.invoke('mcp:save', s),
  mcpDelete: (id: string) => ipcRenderer.invoke('mcp:delete', id),
  mcpToggle: (id: string, enabled: boolean) => ipcRenderer.invoke('mcp:toggle', id, enabled),
  mcpProbe: (id: string) => ipcRenderer.invoke('mcp:probe', id),
  mcpTools: () => ipcRenderer.invoke('mcp:tools'),
  // Skills
  skillsList: () => ipcRenderer.invoke('skills:list'),
  // Window management
  windowOpen: () => ipcRenderer.invoke('window:open'),
  windowList: () => ipcRenderer.invoke('window:list'),
  // Token Stats
  tokenStatsDaily: () => ipcRenderer.invoke('tokenStats:daily'),
  tokenStatsByConversation: () => ipcRenderer.invoke('tokenStats:byConversation'),
  tokenStatsSummary: () => ipcRenderer.invoke('tokenStats:summary'),
  // MaxMode
  chatMaxmode: (opts: any) => ipcRenderer.invoke('chat:maxmode', opts),
  onMaxmodeToken: (cb: any) => { const h = (_: any, d: any) => cb(d); ipcRenderer.on('chat:maxmode:token', h); return () => ipcRenderer.removeListener('chat:maxmode:token', h) },
  onMaxmodeThinking: (cb: any) => { const h = (_: any, d: any) => cb(d); ipcRenderer.on('chat:maxmode:thinking', h); return () => ipcRenderer.removeListener('chat:maxmode:thinking', h) },
  onMaxmodeDone: (cb: any) => { const h = (_: any, d: any) => cb(d); ipcRenderer.on('chat:maxmode:done', h); return () => ipcRenderer.removeListener('chat:maxmode:done', h) },
  onMaxmodeJudge: (cb: any) => { const h = (_: any, d: any) => cb(d); ipcRenderer.on('chat:maxmode:judge', h); return () => ipcRenderer.removeListener('chat:maxmode:judge', h) },
  // Goal Judge
  chatGoalJudge: (opts: any) => ipcRenderer.invoke('chat:goalJudge', opts),
  // Analytics
  analyticsHeatmap: () => ipcRenderer.invoke('analytics:heatmap'),
  analyticsSummary: () => ipcRenderer.invoke('analytics:summary'),
  // App lifecycle
  appReady: () => ipcRenderer.invoke('app:ready'),
})